// Mirror every third-party front-end asset into the repo so the pages load
// nothing from external domains (no CDN, no Google Fonts → no tracker
// classification, no cookies, no third-party availability risk).
//
//   Fonts  → assets/fonts/<family>-<style>-<weight>-<subset>.woff2
//            + one stylesheet per page: assets/fonts/site.css, complorama.css
//   Libs   → vendor/<file>.js  (React, ReactDOM, hls.js, framer-motion)
//
// Idempotent: files already on disk are skipped. Designed for the GitHub
// runner (.github/workflows/tools-vendor-assets.yml) — the local sandbox
// can't reach these hosts. Re-run after bumping a version or adding a
// weight; commit the result.

import { mkdir, writeFile, stat } from 'node:fs/promises';
import path from 'node:path';

const ROOT = process.cwd();

// Same request each page used to make to Google Fonts. Keeping the exact
// families/weights means zero visual change.
const FONT_SHEETS = {
  site:       'https://fonts.googleapis.com/css2?family=Instrument+Serif:ital@0;1&family=Barlow:wght@300;400;500;600&display=swap',
  complorama: 'https://fonts.googleapis.com/css2?family=Archivo:wght@400;500;600;700;800&family=DM+Mono:wght@400;500&family=Fraunces:ital,wght@0,400;1,400;1,700&display=swap',
};
// Only these Unicode subsets are kept — the site is French; cyrillic,
// greek and vietnamese blocks would be dead bytes.
const SUBSETS = new Set(['latin', 'latin-ext']);

const LIBS = [
  ['https://unpkg.com/react@18.3.1/umd/react.production.min.js',         'vendor/react.production.min.js'],
  ['https://unpkg.com/react-dom@18.3.1/umd/react-dom.production.min.js', 'vendor/react-dom.production.min.js'],
  ['https://cdn.jsdelivr.net/npm/hls.js@1.6.15/dist/hls.min.js',         'vendor/hls.min.js'],
  ['https://unpkg.com/framer-motion@10.18.0/dist/framer-motion.js',      'vendor/framer-motion.js'],
];

// A modern desktop Chrome UA makes Google return woff2 + unicode-range
// blocks (older UAs get ttf and no subsetting).
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36';

async function exists(p) { try { return (await stat(p)).size > 0; } catch { return false; } }

async function fetchBytes(url) {
  const res = await fetch(url, { headers: { 'User-Agent': UA }, redirect: 'follow' });
  if (!res.ok) throw new Error(`HTTP ${res.status} ${url}`);
  return Buffer.from(await res.arrayBuffer());
}

async function save(rel, bytes) {
  const abs = path.join(ROOT, rel);
  await mkdir(path.dirname(abs), { recursive: true });
  await writeFile(abs, bytes);
  console.log(`  ✓ ${rel} (${(bytes.length / 1024).toFixed(1)} KB)`);
}

const slug = s => s.toLowerCase().replace(/['"]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

async function vendorFonts(name, cssUrl) {
  console.log(`\nFonts · ${name}`);
  const css = (await fetchBytes(cssUrl)).toString('utf8');
  // Google emits "/* latin */\n@font-face { … }" pairs; split on the comment.
  const blocks = css.split(/\/\*\s*([a-z0-9-]+)\s*\*\//).slice(1); // [subset, block, subset, block…]
  const out = [];
  for (let i = 0; i < blocks.length; i += 2) {
    const subset = blocks[i].trim();
    let block = blocks[i + 1];
    if (!SUBSETS.has(subset)) continue;
    const family = (block.match(/font-family:\s*'([^']+)'/) || [])[1];
    const style  = (block.match(/font-style:\s*(\w+)/) || [])[1] || 'normal';
    const weight = (block.match(/font-weight:\s*(\d+)/) || [])[1] || '400';
    const src    = (block.match(/url\((https:\/\/fonts\.gstatic\.com[^)]+)\)/) || [])[1];
    if (!family || !src) continue;
    const file = `${slug(family)}-${style}-${weight}-${subset}.woff2`;
    const rel  = `assets/fonts/${file}`;
    if (!(await exists(path.join(ROOT, rel)))) await save(rel, await fetchBytes(src));
    else console.log(`  · ${rel} (already present)`);
    // Stylesheet lives in the same folder → relative url() works from any page.
    block = block.replace(src, file).trim();
    out.push(`/* ${family} ${style} ${weight} — ${subset} */\n${block}`);
  }
  const header = `/* Self-hosted fonts for "${name}" — generated by scripts/vendor-assets.mjs.\n   Source request: ${cssUrl} */\n\n`;
  await save(`assets/fonts/${name}.css`, Buffer.from(header + out.join('\n\n') + '\n'));
  console.log(`  → ${out.length} @font-face blocks kept (${[...SUBSETS].join(', ')})`);
}

async function vendorLibs() {
  console.log('\nLibraries');
  for (const [url, rel] of LIBS) {
    if (await exists(path.join(ROOT, rel))) { console.log(`  · ${rel} (already present)`); continue; }
    await save(rel, await fetchBytes(url));
  }
}

for (const [name, url] of Object.entries(FONT_SHEETS)) await vendorFonts(name, url);
await vendorLibs();
console.log('\nDone.');
