// Episodes data — Complorama (France Info)
// Source: catalogue Radio France, fetched via Claude Code.
// Most-recent-first ordering. Episode numbers are derived from the "100e
// Complorama" anchor — replace RAW_EPISODES with a fresh fetch to update.

const RAW_EPISODES = [
  { title: "La saga Alex Jones", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/complorama-6612076", img: "https://www.radiofrance.fr/pikapi/images/346b9cab-c8d2-4b5c-a371-d20b45cd00e7/1200x680", youtube: null, description: "Rudy Reichstadt et Tristan Mendès France décryptent et analysent, dans ce nouveau numéro de Complorama le parcours de cet homme considéré comme l'une des figures les plus influentes du conspirationnisme aux Etats-Unis." },
  { title: "Trump et la fracture MAGA", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/complorama-30-avril-8083070", img: "assets/episodes/8d4664e5-c221-4e24-a3e5-2031f562c42e.webp", youtube: "https://www.youtube.com/watch?v=Q37sSG-H_08", description: "Rudy Reichstadt et Tristan Mendès France décryptent et analysent, dans ce nouveau numéro de Complorama comment la \"magasphère\" se divise autour de Donald Trump." },
  { title: "Hongrie : Viktor Orbán en campagne", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/complorama-6976216", img: "assets/episodes/d5ac8a53-743e-49e5-a32f-758c1cd6d117.webp", youtube: "https://www.youtube.com/watch?v=wjqEVrKDgNY", description: "Rudy Reichstadt et Tristan Mendès France décryptent et analysent, dans ce nouveau numéro de Complorama comment le Premier ministre hongrois Viktor Orbán utilise le complotisme comme stratégie électorale." },
  { title: "En attendant les aliens", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/complorama-2400018", img: "assets/episodes/7796482f-f516-49e3-86c6-f1598532c3a7.webp", youtube: "https://www.youtube.com/watch?v=BiXIPwBVwY0", description: "Rudy Reichstadt et Tristan Mendès France décryptent et analysent, dans ce nouveau numéro de Complorama comment le thème des extraterrestres est passé du divertissement populaire à un outil de déstabilisation politique et de désinformation. C" },
  { title: "Complorama spécial Guerre en Iran", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/complorama-1733186", img: "assets/episodes/60790cde-0c17-45ab-8377-9db25aa4e068.webp", youtube: "https://www.youtube.com/watch?v=BBsttFpjLGw", description: "Rudy Reichstadt et Tristan Mendès France décryptent et analysent, dans ce nouveau numéro de Complorama comment l" },
  { title: "Le complotisme boosté à l’IA", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/complorama-9433022", img: "assets/episodes/c3f63fdf-e466-4f04-9c3a-8368f53c9029.webp", youtube: "https://www.youtube.com/watch?v=sZrYBhbUTIs", description: "Rudy Reichstadt et Tristan Mendès France décryptent et analysent, dans ce nouveau numéro de Complorama, comment l" },
  { title: "Les démons de la complosphère", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/complorama-9520870", img: "assets/episodes/eabde422-204a-4b4d-a220-57aa7824b648.webp", youtube: "https://www.youtube.com/watch?v=K-_SY7IGOZk", description: "Rudy Reichstadt et Tristan Mendès France décryptent et analysent, dans ce nouveau numéro de Complorama, comment la complosphère utilise la rhétorique démoniaque. \"Les démons de la complosphère\", c" },
  { title: "Le Davos des complotistes", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/complorama-9243030", img: "assets/episodes/eb437276-87d7-4560-a41f-08ec588c1ba9.webp", youtube: "https://www.youtube.com/watch?v=ndz43WZuDps", description: "Rudy Reichstadt et Tristan Mendès France décryptent et analysent, dans ce nouveau numéro de Complorama comment la complosphère voit le Forum Economique Mondial" },
  { title: "Complorama : le Venezuela vu de la complosphère", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/complorama-1941086", img: "assets/episodes/382ece95-f5fe-4765-b4ab-8eb5d0351462.webp", youtube: "https://www.youtube.com/watch?v=31WKG8Z6rto", description: "Rudy Reichstadt et Tristan Mendès France décryptent et analysent, dans ce nouveau numéro de Complorama l" },
  { title: "PODCAST. La 100e de Complorama", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/complorama-6775353", img: "assets/episodes/5b84d509-d42e-4eb9-b1d1-97d9bfa3a708.webp", youtube: "https://www.youtube.com/watch?v=Oem1jxpcizQ", description: "Rudy Reichstadt et Tristan Mendès France décryptent et analysent, dans ce 100e épisode, l" },
  { title: "Epstein, l'obsession complotiste", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/complorama-3932564", img: "assets/episodes/077978f1-e113-482d-b63e-9aa084ccf2d3.webp", youtube: "https://www.youtube.com/watch?v=GTYV28BNgOk", description: "Dans ce 99è numéro de Complorama nous revenons avec Rudy Reichstadt et Tristan Mendès-France sur l" },
  { title: "PODCAST. Quand la complosphère s'empare du climat", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/complorama-3357361", img: "assets/episodes/21f3d4a0-3607-4dc7-a235-c21f7589090a.webp", youtube: null, description: "Le 98è numéro de Complorama s" },
  { title: "PODCAST. La complosphère mondiale et Brigitte Macron", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/podcast-la-complosphere-mondiale-et-brigitte-macron-5570460", img: "assets/episodes/b63f5a2d-5872-45db-a50f-93480ae27119.webp", youtube: "https://www.youtube.com/watch?v=v2GhU9M-a9Y", description: "Complorama revient sur le procès pour cyberharcèlement contre Brigitte Macron. Rudy Reichstadt et Tristan Mendès-France examinent les lignes de défense des dix prévenus et analysent la généalogie de la rumeur." },
  { title: "Antivax, le retour", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/podcast-antivax-le-retour-3433552", img: "assets/episodes/150a6599-35b6-4360-8a16-23f41fe1a492.webp", youtube: "https://www.youtube.com/watch?v=qVsDhuLyaZc", description: "Complorama explore le renouveau du mouvement anti-vaccin et son lien avec la complosphère en France et à l" },
  { title: "PODCAST. La complosphère mondiale et Brigitte Macron", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/podcast-la-complosphere-mondiale-et-brigitte-macron-8431389", img: "assets/episodes/b63f5a2d-5872-45db-a50f-93480ae27119.webp", youtube: null, description: "Complorama revient sur le procès pour cyberharcèlement contre Brigitte Macron. Rudy Reichstadt et Tristan Mendès-France examinent les lignes de défense des dix prévenus et analysent la généalogie de la rumeur." },
  { title: "Demain les MedBeds ?", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/demain-les-medbeds-5322920", img: "assets/episodes/3673186d-54b6-4f9c-b0c2-37691b528d07.webp", youtube: "https://www.youtube.com/watch?v=Ev1cYJdvHNk", description: "Donald Trump a publié puis supprimé une vidéo sur son réseau social, dans laquelle il annonce des MedBeds pour tous les Américains. Une vidéo générée par IA. Ces lits médicalisés n" },
  { title: "Podcast. La complosphère et l'assassinat de Charlie Kirk", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/podcast-la-complosphere-et-l-assassinat-de-charlie-kirk-6793545", img: "assets/episodes/49dc6c0f-1c11-484f-96ea-7154351a1c7f.webp", youtube: "https://www.youtube.com/watch?v=H6lNYghXN3c", description: "Cet épisode du podcast Complorama se concentre sur l" },
  { title: "\"Bloquons tout\" : la complosphère en embuscade le 10 septembre ?", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/podcast-bloquons-tout-la-complosphere-en-embuscade-le-10-septembre-9852523", img: "assets/episodes/1c9e8394-a3b3-4cf1-80fc-415d2b1af56b.webp", youtube: "https://www.youtube.com/watch?v=8M5AZHW480Q", description: "\"Le 10 septembre, le peuple reprend la main\". Si le tout premier message est apparu en mai dernier, l" },
  { title: "La Russie, l'eldorado des complotistes français", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/la-russie-l-eldorado-des-complotistes-francais-3514278", img: "assets/episodes/1688fc7c-82b6-45d5-b348-f6b44fc1fc1f.webp", youtube: "https://www.youtube.com/watch?v=xSSQ82UwGd4", description: "La Russie de Vladimir Poutine exerce une fascination sur de nombreux complotistes français. Certains n" },
  { title: "Aux États-Unis, le complotisme contre la science", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/aux-etats-unis-le-complotisme-contre-la-science-1168735", img: "assets/episodes/38dabc9b-ce8e-46c3-9920-57d1dc9fb632.webp", youtube: "https://www.youtube.com/watch?v=BXVF2D9G9bc", description: "Depuis le début du second mandat de Donald Trump, la science et ses institutions subissent des attaques sans précédent aux États-Unis. Les coupes budgétaires, les purges sémantiques, ou encore les menaces et intimidations visent universités, revues scientifiques et agences de l" },
  { title: "\"Génocide blanc\" en Afrique du Sud : itinéraire d'une théorie complotiste", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/genocide-blanc-en-afrique-du-sud-itineraire-d-une-theorie-complotiste-3138298", img: "assets/episodes/667ca888-078b-4b77-ba45-ebfc46b4df04.webp", youtube: "https://www.youtube.com/watch?v=htJOWGqdfPw", description: "En recevant le président sud-africain dans le bureau ovale, Donald Trump a diffusé des vidéos montrant, selon lui, des \"familles entières\" d" },
  { title: "Roumanie, le complotisme à l'heure des élections", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/roumanie-le-complotisme-a-l-heure-des-elections-4919353", img: "assets/episodes/0f69178e-0e7a-473f-ad26-b594cb4a2de6.webp", youtube: "https://www.youtube.com/watch?v=UMI0Xl2gRbQ", description: "À deux jours de l’élection présidentielle roumaine, les théories complotistes s’invitent dans le débat électoral. Nationaliste, antivax et fan de Donald Trump, le candidat d’extrême droite George Simion donne du grain à moudre à la sphère complotiste déjà bien implantée en Roumanie." },
  { title: "Quatre-vingt ans après, la mort d’Adolf Hitler réveille la complosphère", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/quatre-vingt-ans-apres-la-mort-d-adolf-hitler-reveille-la-complosphere-8831796", img: "assets/episodes/7350df6c-7798-420f-a84f-731b987286a8.webp", youtube: "https://www.youtube.com/watch?v=UyE7gAmLn1k", description: "Quatre-vingt ans après sa mort, les théories complotistes autour d" },
  { title: "Canada : le complotisme à l'heure des élections", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/canada-le-complotisme-a-l-heure-des-elections-6097449", img: "assets/episodes/608a20cb-8a6d-4cea-ba14-5edeedc1b12f.webp", youtube: "https://www.youtube.com/watch?v=zQemCvFC6Js", description: "À la fin du mois, les Canadiens se rendront aux urnes afin de voter aux élections fédérales anticipées afin d" },
  { title: "L'Otan dans l’imaginaire complotiste", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/l-otan-dans-l-imaginaire-complotiste-4006197", img: "assets/episodes/af581429-e89d-4948-985d-2b990f4c476d.webp", youtube: "https://www.youtube.com/watch?v=w3FytzenhWE", description: "Alors que Donald Trump remet en question l" },
  { title: "Le Covid-19, la grande bascule complotiste", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/le-covid-19-la-grande-bascule-complotiste-9607240", img: "assets/episodes/1440277b-54f0-4442-8ed7-3cc69acd5078.webp", youtube: "https://www.youtube.com/watch?v=lJOadM9Rpg0", description: "La pandémie de Covid-19 a marqué un tournant majeur dans l" },
  { title: "Quand le pape François était dans le viseur des complotistes", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/le-pape-dans-le-viseur-des-complotistes-8271047", img: "assets/episodes/1f51722b-7300-49ff-aec5-892c26d458ac.webp", youtube: "https://www.youtube.com/watch?v=w0VtdU36n1A", description: "Le pape François était-il secrètement un franc-maçon, un agent du nouvel ordre mondial, ou même un pédocriminel ? Le souverain pontife argentin, mort lundi à l" },
  { title: "Des services secrets américains au Mossad, le monde du renseignement au cœur du complotisme", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/des-services-secrets-americains-au-mossad-le-monde-du-renseignement-au-coeur-du-complotisme-7667491", img: "assets/episodes/050e560b-bcc8-4f5c-b736-5bebfd597917.webp", youtube: "https://www.youtube.com/watch?v=b2cUmWgxkSE", description: "Aux Etats-Unis, après Tulsi Gabbard à la tête du renseignement national, c" },
  { title: "L'intelligence artificielle et le complotisme", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/l-intelligence-artificielle-et-le-complotisme-9921300", img: "assets/episodes/d873fe82-d929-4294-9b4f-85373a924e27.webp", youtube: "https://www.youtube.com/watch?v=T0_z5MTpuzs" },
  { title: "Le négationnisme et la complosphère", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/le-negationnisme-et-la-complosphere-7276248", img: "assets/episodes/858c9f7c-14fa-45dc-b76a-1b5ed45a042d.webp", youtube: null, description: "Le négationnisme, cette remise en cause du génocide des Juifs par les nazis, est un système de pensée, une idéologie qui cherche à réhabiliter le nazisme en niant les crimes de la Shoah. Cet épisode explore les racines du négationnisme, ses figures clés, et son lien étroit avec le complotisme." },
  { title: "Allemagne : le complotisme à l’aube des élections", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/allemagne-le-complotisme-a-l-aube-des-elections-2036685", img: "assets/episodes/5365dfef-eb64-4ecf-9e74-c5ae654458cd.webp", youtube: null },
  { title: "Complotisme : le guide de survie pour les fêtes", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/complotisme-le-guide-de-survie-pour-les-fetes-6005608", img: "assets/episodes/7b0f657d-9104-4865-932b-2ecefb754299.webp", youtube: "https://www.youtube.com/watch?v=j5Nr3v0OnJI", description: "Les fêtes de fin d" },
  { title: "La communauté LGBT+, cible privilégiée des complotistes", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/podcast-la-communaute-lgbt-cible-privilegiee-des-complotistes-5393813", img: "assets/episodes/b9d8734e-be52-4b78-90b8-98218e854d6f.webp", youtube: "https://www.youtube.com/watch?v=kVHMpLOtoB0" },
  { title: "COP29 : le changement climatique dans le radar des complotistes", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/cop29-le-changement-climatique-dans-le-radar-des-complotistes-3948010", img: "assets/episodes/14508a66-86e5-4ba2-b3f0-603ce04537a8.webp", youtube: "https://www.youtube.com/watch?v=_pJJR_pR1qQ", description: "La COP29, le retour de Donald Trump, les inondations en Espagne... L" },
  { title: "Donald Trump, le retour du complotisme à la Maison Blanche", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/donald-trump-le-retour-du-complotisme-a-la-maison-blanche-8163584", img: "assets/episodes/7c9f4099-e72d-49ca-8518-dc82f09f812c.webp", youtube: "https://www.youtube.com/watch?v=Z0ubzv5t2tM", description: "Exaltée par ce nouveau mandat de Donald Trump, la sphère complotiste n’espère qu’une chose : que le futur président réforme en profondeur le pays et puisse vaincre \"l" },
  { title: "Elon Musk, pilier complotiste de la campagne de Donald Trump", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/elon-musk-pilier-complotiste-de-la-campagne-de-donald-trump-6582061", img: "assets/episodes/5a19f149-b54e-46d2-b99f-a7bcbc26c9af.webp", youtube: "https://www.youtube.com/watch?v=hUwHW8uDeEU", description: "Le milliardaire est un fervent partisan de Donald Trump. Mais son soutien va bien au-delà des simples déclarations. Cet épisode de Complorama explore comment Elon Musk soutient activement la campagne de Donald Trump, alimentant un climat de désinformation et de manipulation." },
  { title: "De l'Atlantide aux pyramides, quand la complosphère revisite les grands mythes historiques", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/de-l-atlantide-aux-pyramides-quand-la-complosphere-revisite-les-grands-mythes-historiques-7457279", img: "assets/episodes/dbe6beae-d06c-4330-a7ee-3808cefb6738.webp", youtube: "https://www.youtube.com/watch?v=XNJbunt1h9I", description: "Dans ce nouvel épisode de Complorama, Tristan Mendès France et Rudy Reichstadt explorent la fascination de la complosphère pour les mythes historiques, examinant comment ces récits sont déformés et instrumentalisés à des fins idéologiques." },
  { title: "États-Unis : quand le complotisme s'installe dans la campagne présidentielle", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/etats-unis-quand-le-complotisme-s-installe-dans-la-campagne-presidentielle-2368490", img: "assets/episodes/c721ab86-6c84-448b-9296-5f662ee8e659.webp", youtube: "https://www.youtube.com/watch?v=-mjyA1iQylc", description: "Les théories du complot sont la raison de vivre des partisans de Donald Trump, qui semblent préférer cette vérité alternative où Kamala Harris se servirait du vote des immigrés pour truquer l" },
  { title: "D'Hugo Chavez à Nicolas Maduro, le complotisme au Venezuela", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/d-hugo-chavez-a-nicolas-maduro-le-complotisme-au-venezuela-4295612", img: "assets/episodes/921477a4-5d13-4105-bb0b-a420df25dd00.webp", youtube: "https://www.youtube.com/watch?v=RkG4HGkkJp8", description: "Nicolas Maduro a été réélu à la tête du Venezuela le 28 juillet dernier, mais l’opposition dénonce une fraude électorale massive. Tristan Mendès France et Rudy Reichstadt décryptent et analysent les théories du complot dont est friand le régime vénézuélien." },
  { title: "Les Jeux olympiques du complotisme", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/podcast-les-jeux-olympiques-du-complotisme-8352365", img: "assets/episodes/3c8b7205-5bce-4520-8823-3fe3088ad08b.webp", youtube: null, description: "Un plan secret de propagation d" },
  { title: "Dissolution de l'Assemblée nationale, élections européennes… La complosphère en embuscade", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/dissolution-de-l-assemblee-nationale-elections-europeennes-la-complosphere-en-embuscade-3069262", img: "assets/episodes/b8f730bc-9032-447f-b053-a8e43bde0e44.webp", youtube: null, description: "Alors que la campagne des élections européennes a été une occasion pour certains candidats de diffuser leur discours complotiste et de crier à la fraude électorale, l" },
  { title: "Les prophéties apocalyptiques de la complosphère", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/les-propheties-apocalyptiques-de-la-complosphere-2242962", img: "assets/episodes/1c75b530-af7d-4184-b30a-dfd7b9ea3e55.webp", youtube: null, description: "La complosphère s’empare des grandes peurs qui traversent nos sociétés, réactivant le thème de la \"fin du monde\". Les complotistes se sont engouffrés dans la brèche à coup de prophéties erronées, de prédictions de \"guerre thermonucléaire\" ou de \"génocide vaccinal\" démenties par la réalité." },
  { title: "Le complotisme en Inde à l'heure des élections", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/le-complotisme-en-inde-a-l-heure-des-elections-2115883", img: "assets/episodes/2cfe5e6a-4f87-4289-bd3d-0e61fdcc82c5.webp", youtube: null, description: "Les électeurs indiens se pressent dans les bureaux de vote pour élire les 543 députés de la chambre basse du Parlement. Au pouvoir depuis dix ans, le Premier ministre Narendra Modi mène sur la \"plus grande démocratie du monde\" une politique autoritaire où le complotisme n’est jamais loin." },
  { title: "Agent du Pentagone, rituels sataniques, Illuminati... Taylor Swift au cœur de théories du complot", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/taylor-swift-au-coeur-de-theories-du-complot-7000036", img: "assets/episodes/3e2dc28b-1fa6-4e42-a049-a7db94657267.webp", youtube: null, description: "À seulement 34 ans, la pop star devient la première artiste milliardaire uniquement grâce aux revenus de sa musique. Une notoriété qui n" },
  { title: "Les \"citoyens souverains\", de la contestation au complotisme", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/les-citoyens-souverains-de-la-mouvance-contestataire-au-complotisme-9016330", img: "assets/episodes/aa11e04b-13dc-4578-9ebc-2bb4cb6eccdc.webp", youtube: null, description: "La vidéo d" },
  { title: "Attentats, accidents, disparitions… Les catastrophes aériennes au cœur des récits complotistes", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/attentats-accidents-disparitions-les-catastrophes-aeriennes-au-coeur-des-recits-complotistes-9080545", img: "assets/episodes/a9d56005-9dbf-4817-a2f3-e93b35153310.webp", youtube: null, description: "Des origines du génocide des Tutsi au Rwanda jusqu" },
  { title: "PODCAST. Brigitte Macron, Michelle Obama, Kate Middleton... Ces femmes visées par le complotisme", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/brigitte-macron-michelle-obama-kate-middleton-ces-femmes-visees-par-le-complotisme-1901249", img: "assets/episodes/f3f5e623-adaf-4279-88ed-4fd1f912f7fb.webp", youtube: null, description: "Une théorie nauséabonde a été déterrée par la complosphère : Brigitte Macron serait une femme transgenre. Cette théorie complotiste pourrait n’avoir aucun écho si l’extrême droite américaine ne s’en était pas emparée à la mi-mars. Mais l" },
  { title: "Le fantasme complotiste autour de la dynastie Rothschild", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/podcast-le-fantasme-complotiste-autour-de-la-dynastie-rothschild-3051444", img: "assets/episodes/34e8e3eb-e348-4d32-8b90-a781a9a2b0e6.webp", youtube: null, description: "Mainmise sur les banques centrales, influence sur les présidents… Depuis près de deux siècles, de nombreuses théories du complot fleurissent autour de la famille Rothschild." },
  { title: "Mort d'Alexeï Navalny : l'opposant russe dans le collimateur des complotistes", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/mort-d-alexei-navalny-l-opposant-russe-dans-le-collimateur-des-complotistes-3038205", img: "assets/episodes/9502098e-02a4-4ef2-86bd-0ee6f0f9eda7.webp", youtube: null, description: "Agent de la CIA, complot de l" },
  { title: "Colère des agriculteurs : quand la sphère complotiste tente de récupérer les mouvements sociaux", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/colere-des-agriculteurs-quand-la-sphere-complotiste-tente-de-recuperer-les-mouvements-sociaux-1013817", img: "assets/episodes/25ae6829-7aec-4715-94ac-c1107797c49e.webp", youtube: null, description: "La mobilisation des agriculteurs a été vue et entendue en France comme ailleurs. Sur les réseaux sociaux, le hashtag #AgriculteursEnColère a rapidement été propulsé par des adeptes de théories complotistes. Avec un seul but : profiter de cette colère pour faire passer leur message." },
  { title: "Covid-19 : Didier Raoult, figure adulée par la complosphère", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/covid-19-didier-raoult-figure-adulee-par-la-complosphere-2330100", img: "assets/episodes/91474af4-17b3-47d8-b676-a6445425aa78.webp", youtube: null, description: "En quelques années, le microbiologiste, à la personnalité et aux pratiques controversées, est devenu une personnalité phare pour les complotistes." },
  { title: "Jeffrey Epstein, l’affaire de tous les fantasmes pour la complosphère", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/jeffrey-epstein-l-affaire-de-tous-les-fantasmes-pour-la-complosphere-1267530", img: "assets/episodes/f18c7914-6767-48fe-afb9-35b77954c7e4.webp", youtube: null, description: "Depuis des années, l" },
  { title: "Les dérives sectaires et complotistes du mouvement raëlien", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/les-derives-sectaires-et-complotistes-du-mouvement-raelien-5096118", img: "assets/episodes/694e025e-154c-4f60-a719-df6442180728.webp", youtube: null, description: "La secte Raël, fondée par Claude Vorilhon et qui a fêté mercredi 13 décembre ses 50 ans d" },
  { title: "De Vinted au Pizzagate, la théorie du complot du trafic d’enfants sur Internet", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/de-vinted-au-pizzagate-la-theorie-du-complot-du-trafic-d-enfants-sur-internet-7864273", img: "assets/episodes/07eb23b2-ad8b-4f8b-a642-f2df32e74fd5.webp", youtube: null, description: "Des objets vendus à des prix exorbitants ont attiré l" },
  { title: "L'assassinat de John Fitzgerald Kennedy, 60 ans de théories du complot", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/l-assassinat-de-john-fitzgerald-kennedy-60-ans-de-theories-du-complot-1119657", img: "assets/episodes/c26155a8-deaf-4142-9009-e0be98fd9684.webp", youtube: null, description: "Le 22 novembre 1963, le président des États-Unis est assassiné lors d’une visite officielle à Dallas (Texas). Le principal suspect, Lee Harvey Oswald, est arrêté puis tué deux jours plus tard. Le pays reste marqué par cet événement qui a nourri de nombreuses thèses conspirationnistes." },
  { title: "Hongrie : le complotisme à l’ère de Viktor Orban", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/hongrie-le-complotisme-a-l-ere-de-viktor-orban-8783160", img: "assets/episodes/d71f17ba-7f64-4233-bd7d-cd48fe0f8109.webp", youtube: null, description: "La rencontre entre le Premier ministre hongrois Viktor Orban et le président russe Vladimir Poutine, le 17 octobre en Chine, met dans l’embarras l’Europe. Pour légitimer sa politique radicale qui lui vaut d" },
  { title: "Guerre entre Israël et le Hamas, un nouveau moment complotiste", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/guerre-entre-israel-et-le-hamas-un-nouveau-moment-complotiste-6118752", img: "assets/episodes/e66fa36f-3338-4010-b3ad-ef23a8168b47.webp", youtube: null, description: "Depuis le 7 octobre, les hostilités entre le Hamas et Israël font l’objet d’une déferlante de théories du complot et de désinformation sur les réseaux sociaux. Cette vague inédite de contenus conspirationnistes met à l’épreuve les politiques de modérations des plateformes, déjà pointées du doigt." },
  { title: "De la \"loi Evras\" aux ABCD de l'égalité : quand les complotistes s'attaquent à l'école", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/de-la-loi-evras-aux-abcd-de-l-egalite-quand-les-complotistes-s-attaquent-a-l-ecole-9403151", img: "assets/episodes/b1d0f390-2503-4089-affc-b0aac4552901.webp", youtube: null, description: "En Belgique, le programme Evras subit une vague de désinformation des milieux conservateurs et religieux radicaux, qu" },
  { title: "De Thierry Ardisson à Cyril Hanouna, quand le complotisme s’invite à la télévision", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/de-thierry-ardisson-a-cyril-hanouna-quand-le-complotisme-s-invite-a-la-television-8447818", img: "assets/episodes/40a9317f-3fe8-4648-82c2-0a95136da90b.webp", youtube: null, description: "Il n’est pas rare d’entendre des théories du complot sur les plateaux de télévision. L’infotainment est devenu un business depuis les années 90. La recherche du buzz et des dérapages a ouvert le champ libre aux complotistes sur le petit écran." },
  { title: "De Donald Trump au Nuremberg 2.0 : quand les complotistes font le procès de la justice", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/quand-les-complotistes-font-le-proces-de-la-justice-4881168", img: "assets/episodes/d104a2ba-a03b-445f-bf45-456dfc9222b2.webp", youtube: null, description: "Donald Trump est de nouveau inculpé par la justice américaine pour ses pressions électorales lors de l’élection présidentielle de 2020 en Géorgie. L’ex-président des Etats-Unis mais d’autres aussi, en France, se disent parfois victimes d’une instrumentalisation de la justice." },
  { title: "Quand la complosphère s'empare des ovnis", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/quand-la-complosphere-s-empare-des-ovnis-8300471", img: "assets/episodes/5eb125e3-e31d-4f05-8598-838242238e49.webp", youtube: null, description: "Les déclarations d" },
  { title: "De la maladie X au \"nouvel ordre mondial\" : quand les complotistes s'attaquent à l'ONU", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/de-la-maladie-x-au-nouvel-ordre-mondial-quand-les-complotistes-s-attaquent-a-l-onu-4680509", img: "assets/episodes/99a3c6d1-e39a-4057-a2b6-43b545a08629.webp", youtube: null, description: "La maladie X mentionnée par l" },
  { title: "La Turquie complotiste à l'heure de l'élection présidentielle", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/la-turquie-complotiste-a-l-heure-de-l-election-presidentielle-6708415", img: "assets/episodes/95e77384-7dc0-4620-a374-6baaade112a5.webp", youtube: null, description: "À quelques jours du second tour en Turquie, Recep Tayyip Erdogan se retrouve en position de force face à son adversaire Kemal Kiliçdaroglu. Le président sortant s’est installé au fil des années en maître dans l’art de fabriquer des théories du complot pour se maintenir au pouvoir." },
  { title: "Assassinat de Shinzo Abe, Covid-19, Fukushima : le complotisme au Japon", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/japon-le-complotisme-au-pays-du-soleil-levant-8383232", img: "assets/episodes/43260c88-8c3d-42e0-a80d-c66b6879d6a0.webp", youtube: null, description: "Les manifestations dénonçant la gestion de la crise du Covid-19 par les autorités japonaises se poursuivent, distillant l" },
  { title: "Clinton, Deep State, QAnon... Donald Trump et les théories du complot", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/clinton-deep-state-qanon-donald-trump-et-les-theories-du-complot-2161455", img: "assets/episodes/4112e544-5772-467e-83ed-d9a617ebbd20.webp", youtube: null, description: "Après son inculpation le 4 avril dernier par un tribunal de New York, Donald Trump, se dit victime d" },
  { title: "Adrénochrome, crimes rituels : le sang au cœur du complotisme", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/adrenochrome-crimes-rituels-le-sang-au-coeur-du-complotisme-7805665", img: "assets/episodes/e524f2cf-d446-41ef-9a17-6e8b1ce2c02f.webp", youtube: null, description: "Le mythe de l" },
  { title: "Des réseaux sociaux à la politique, les stratégies du complotisme climatique", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/des-reseaux-sociaux-a-la-politique-les-strategies-du-complotisme-climatique-4808224", img: "assets/episodes/7127bbd3-3799-46e8-a90c-64f7ede73a97.webp", youtube: null, description: "C’est devenu l’activité principale des climatosceptiques sur internet : délégitimer le travail des experts du Giec, dont la synthèse du sixième rapport d" },
  { title: "Guerre en Ukraine : un an de théories du complot au service de la propagande", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/guerre-en-ukraine-un-an-de-theories-du-complot-au-service-de-la-propagande-7008439", img: "assets/episodes/9eb7564f-da7a-4fdf-8da3-1765e775d8e0.webp", youtube: null, description: "Le 24 février 2022, Vladimir Poutine annonçait sa décision d’envahir l’Ukraine pour \"dénazifier\" le pays. Un an plus tard, la complosphère a toujours les yeux rivés sur l’Ukraine, chaque événement n’est selon elle qu’un fake orchestré par l’Occident et la \"junte nazie\" au pouvoir à Kiev." },
  { title: "TikTok, Roblox, Fortnite : la jeunesse dans le viseur des complotistes", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/tiktok-roblox-fortnite-la-jeunesse-dans-le-viseur-des-complotistes-4351044", img: "assets/episodes/1073fc96-1607-4182-9026-10b1fd6993d2.webp", youtube: null, description: "S’ils sont encore minoritaires, certains jeunes Français semblent clairement être plus méfiants et sensibles à la désinformation que leurs aînés. Sont-ils aujourd’hui devenus une cible privilégiée de la complosphère ?" },
  { title: "ChatGPT : l'intelligence artificielle au service du complotisme ?", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/chatgpt-l-intelligence-artificielle-au-service-du-complotisme-1527533", img: "assets/episodes/fa025aad-6e5f-4e20-b569-c6c0c51bf1da.webp", youtube: null, description: "Ce robot conversationnel est capable d" },
  { title: "Elon Musk et Twitter : vers plus d’extrémisme et de complotisme sur le réseau social ?", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/elon-musk-et-twitter-vers-plus-d-extremisme-et-de-complotisme-sur-le-reseau-social-8604807", img: "assets/episodes/3187508f-4b33-495f-afdc-d0466898270d.webp", youtube: null, description: "Depuis sa prise de pouvoir de Twitter, Elon Musk multiplie les clins d" },
  { title: "Iran : le complotisme à l’heure des manifestations", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/iran-le-complotisme-a-l-heure-des-manifestations-6124511", img: "assets/episodes/d525f752-3864-44a2-8f03-0d7a674833cd.webp", youtube: null, description: "Israël et des services de renseignements occidentaux accusés de “planifier” une guerre civile : c’est l’un des narratifs complotistes générés par la révolte en Iran. Des théories qui peuvent venir de l’intérieur même du pays, pour tenter de convaincre l’opinion iranienne, mais pas seulement." },
  { title: "Des cryptomonnaies aux monnaies alternatives : le complotisme monétaire", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/des-cryptomonnaies-aux-monnaies-alternatives-le-complotisme-monetaire-9082278", img: "assets/episodes/f6eec07b-fe07-475b-b9d6-317eea79d739.webp", youtube: null, description: "C’est un crash éclair qui a abasourdi le monde de la cryptomonnaie : la plateforme FTX s’est déclarée en faillite. Et ça n’a pas manqué de générer des interprétations complotistes. Car crypto ou pas, la monnaie suscite depuis longtemps des fantasmes de manipulation par les puissants." },
  { title: "Climat : les \"chemtrails\", une théorie du complot venue du ciel", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/climat-les-chemtrails-une-theorie-du-complot-venue-du-ciel-4501530", img: "assets/episodes/32527c3e-278e-418e-91f4-9bac0aa2b9f8.webp", youtube: null, description: "La COP27 donne l’occasion à certains climatosceptiques de recycler une théorie conspirationniste bien connue : les \"chemtrails\", ou quand les traînées blanches laissées derrière le passage des avions seraient manipulées pour nuire à la population." },
  { title: "D’Elon Musk à Kanye West : contrôler une plateforme favorise-t-il le complotisme ?", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/d-elon-musk-a-kanye-west-controler-une-plateforme-favorise-t-il-le-complotisme-5666727", img: "assets/episodes/9e639770-1667-467d-b764-3531a69b55a4.webp", youtube: null, description: "Après la polémique autour des propos à caractère antisémite de Kanye West, le rappeur américain est en passe de devenir le futur patron du réseau social Parler. A-t-il été inspiré par le libertarien Elon Musk, nouveau patron de Twitter ?" },
  { title: "Des drapeaux russes au Burkina Faso à Wagner : la propagande complotiste russe sur le continent africain", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/des-drapeaux-russes-au-burkina-faso-a-wagner-la-propagande-complotiste-russe-sur-le-continent-africain-3712775", img: "assets/episodes/b08efca4-8466-4463-ae21-fcade6707813.webp", youtube: null, description: "Suite au putsch au Burkina Faso, de nombreux drapeaux russes ont été vu dans des manifestations anti-France. Ce soutien affiché à la Russie résulte d’une entreprise d’influence puissante, qui n’hésite pas à utiliser des théories du complot." },
  { title: "Présidentielle au Brésil : le complotisme au service de Jair Bolsonaro", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/presidentielle-au-bresil-le-complotisme-au-service-de-jair-bolsonaro-7705410", img: "assets/episodes/451eef32-b852-487e-9ae7-d5a400d0eaed.webp", youtube: null, description: "Le premier tour de l" },
  { title: "Mort d’Elizabeth II : de la \"reine reptilienne\" au \"meurtre\" de Lady Di, théories du complot autour de la famille royale", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/mort-d-elizabeth-ii-les-theories-du-complot-autour-de-la-famille-royale-britannique-3549579", img: "assets/episodes/b6817486-83fd-49d8-9a9c-a76b8bc2b2ad.webp", youtube: null, description: "Elizabeth II, Lady Di, mais aussi le reste de la famille royale britannique : les théories du complot qui les visent sont nombreuses, et anciennes, et se voient réactivées à l’occasion de la mort de la reine d’Angleterre." },
  { title: "De Doctolib à Pôle emploi, la naturopathie en question", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/de-doctolib-a-pole-emploi-la-naturopathie-en-question-2016509", img: "assets/episodes/ba4f91e4-33f3-4e49-b9b5-4ac275a61065.webp", youtube: null, description: "Fin août, la plateforme Doctolib, au cœur d’une polémique, a supprimé 17 profils de praticiens du bien-être. L’alerte, venue des internautes, marque-t-elle une prise de conscience, quant aux dérives de la naturopathie qui s’offre parfois de bien belles vitrines, sans trop de contrôle ?" },
  { title: "Projet nazi, CIA, cheval de Troie du \"grand remplacement\" : l’Union européenne vue par les complotistes", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/projet-nazi-cia-cheval-de-troie-du-grand-remplacement-l-union-europeenne-vue-par-les-complotistes-2823705", img: "assets/episodes/ff0fe4e1-379e-446c-a9ac-0126d93d207b.webp", youtube: null, description: "L’Ukraine et la Moldavie sont désormais des pays candidats à l’entrée dans l’Union européenne, une institution qui depuis des décennies suscite différentes théories conspirationnistes, que ce soit sur ses origines ou sur son rôle aujourd’hui." },
  { title: "Avortement : quand les complotistes s’attaquent au droit à l’IVG", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/avortement-quand-les-complotistes-s-attaquent-au-droit-a-l-ivg-7073910", img: "assets/episodes/536c1946-8e02-4110-a170-31f76bcddb27.webp", youtube: null, description: "La remise en cause du droit à l’IVG aux États-Unis a relancé, dans ce pays mais également en France, les théories complotistes autour de l’avortement." },
  { title: "Guerre en Ukraine, Covid, Ouïghours : en Chine, un complotisme d’État décomplexé", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/guerre-en-ukraine-covid-ouighours-en-chine-un-complotisme-d-etat-decomplexe-4624397", img: "assets/episodes/a5012149-61df-4077-abb4-86fc13313a3c.webp", youtube: null, description: "La Chine est un émetteur majeur de la propagande complotiste russe sur la guerre en Ukraine. L’occasion d’analyser la politique de Pékin d’utiliser le conspirationnisme comme une véritable arme informationnelle." },
  { title: "WikiLeaks : portrait de Julian Assange, figure controversée au centre de théories du complot", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/wikileaks-portrait-de-julian-assange-figure-controversee-au-centre-de-theories-du-complot-7635818", img: "assets/episodes/9293f272-3b25-4084-b97f-1bc5d8d14946.webp", youtube: null, description: "À travers ses prises de position et ses méthodes parfois critiquées, le fondateur de WikiLeaks a parfois été la cible de théories conspirationnistes... Mais aussi la source." },
  { title: "De Boutcha en Ukraine à la Seconde Guerre mondiale : le complotisme en temps de guerre", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/de-boutcha-en-ukraine-a-la-seconde-guerre-mondiale-le-complotisme-en-temps-de-guerre-4157471", img: "assets/episodes/556b68ce-f581-4b0b-bbe3-c497132281a8.webp", youtube: null, description: "Le massacre de Boutcha a déclenché une déferlante dans les milieux complotistes, réveillant des mécanismes qui ne datent pas de la guerre en Ukraine. Zoom sur les mécanismes de propagande conspirationniste en temps de guerre." },
  { title: "Présidentielle 2022 : l’élection qui serait truquée, cette petite musique du complotisme électoral", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/presidentielle-2022-l-election-qui-serait-truquee-cette-petite-musique-du-complotisme-electoral-6719850", img: "assets/episodes/34363b11-c665-4655-997d-62c677d6e3f8.webp", youtube: null, description: "La théorie selon laquelle l’élection présidentielle ne serait qu’une machination et non un processus démocratique n’est pas nouvelle, elle résonne en France en 2022, y compris à travers les propos de candidats à ce scrutin." },
  { title: "De Booba à Kroc Blanc, du Covid à l’Ukraine : le complotisme dans le rap", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/de-booba-a-kroc-blanc-du-covid-a-l-ukraine-le-complotisme-dans-le-rap-7695979", img: "assets/episodes/1154f74e-d2f9-4525-b8c0-375889ce9411.webp", youtube: null, description: "Une frange minoritaire du rap tombe parfois dans le complotisme, comme lorsque Booba devient l’un des plus gros vecteurs de propagande russe sur les réseaux sociaux francophones." },
  { title: "La guerre en Ukraine, entre propagande russe et complotisme", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/la-guerre-en-ukraine-entre-propagande-russe-et-complotisme-9355565", img: "assets/episodes/fda5e4ff-d354-43bc-8883-231510e010b8.webp", youtube: null, description: "Depuis le début de l’invasion russe en Ukraine, de nombreuses théories conspirationnistes surgissent sur les réseaux sociaux. À cela s’ajoute la propagande de guerre du Kremlin qui souffle sur les braises de la désinformation." },
  { title: "\"Grand remplacement\" : de Renaud Camus à Valérie Pécresse et Éric Zemmour, itinéraire d'une théorie complotiste", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/de-renaud-camus-a-valerie-pecresse-en-passant-par-eric-zemmour-le-parcours-de-la-theorie-du-grand-remplacement-2669634", img: "assets/episodes/8bca056f-476f-4ba6-bf39-4a1c2b7cf862.webp", youtube: null, description: "La théorie du grand remplacement, dont l’usage par Valérie Pécresse lors d’un meeting de la candidate LR à la présidentielle a fait beaucoup de bruit, a une origine et un parcours à forte imprégnation complotiste." },
  { title: "Covid : où en est le complotisme antivax, plus d’un an après le début de la campagne de vaccination ?", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/covid-ou-en-est-le-complotisme-antivax-plus-d-un-an-apres-le-debut-de-la-campagne-de-vaccination-5596302", img: "assets/episodes/0d60e1f1-d540-4d71-b00b-cbfd83dfcd14.webp", youtube: null, description: "Augmentation des cancers, modification de l’ADN ou 5G, disparitions de faux morts du Covid… Les théories du complot autour du vaccin se portent bien, en ce début d’année 2022. Mais le complotisme antivax a évolué, depuis le lancement de la campagne de vaccination il y a un peu plus d’un an." },
  { title: "De Staline à Poutine, le complotisme en Russie", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/de-staline-a-poutine-le-complotisme-en-russie-2335469", img: "assets/episodes/49cf72d3-11ab-4f3a-adf2-8d40210f8b0f.webp", youtube: null, description: "La crise en Ukraine a relancé la puissante machine à désinformation de la Russie, dont le complotisme est l’un des leviers." },
  { title: "Assaut du Capitole : un an après l’attaque, que nous dit-il du complotisme aux États-Unis ?", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/assaut-du-capitole-un-an-apres-l-attaque-que-nous-dit-il-du-complotisme-aux-etats-unis-2850443", img: "assets/episodes/48d99133-533d-48ad-a81f-93481109b591.webp", youtube: null, description: "L’assaut du Capitole, le 6 janvier 2021, est un évènement complotiste majeur, et qui continue d’avoir des conséquences sur la vie américaine. Il révèle la place qu’occupe la mouvance complotiste aujourd’hui aux Etats-Unis, pays dans lequel elle est profondément ancrée, de Kennedy à QAnon." },
  { title: "Fêtes de Noël : quand le complotisme divise dans les familles", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/fetes-de-noel-quand-le-complotisme-divise-dans-les-familles-4365459", img: "assets/episodes/99cb7c14-c1c7-4110-af80-0376e2edfd8e.webp", youtube: null, description: "Les repas de fêtes approchent, et avec eux les discussions parfois mouvementées en famille ou entre amis. Parfois, le complotisme peut entraîner de véritables ruptures des liens entre proches." },
  { title: "COP26, réchauffement : les théories du complot autour du climat", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/cop26-rechauffement-les-theories-du-complot-autour-du-climat-5649462", img: "assets/episodes/ca4e624a-d0c1-4e3c-be8f-2ee6715f60a5.webp", youtube: null, description: "Des \"chemtrails\" au réchauffement climatique, en passant par les incendies géants, le complotisme climatique a de beaux jours devant lui et se nourrit en ce moment de la sémantique sanitaire." },
  { title: "Procès du 13-Novembre : le complotisme n’est jamais loin des attentats", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/proces-du-13-novembre-le-complotisme-n-est-jamais-loin-des-attentats-4384239", img: "assets/episodes/c59b5fcf-f65c-4ca9-ad53-80a49b9e783c.webp", youtube: null, description: "Six ans après les attentats du 13-Novembre, une théorie du complot s’est invitée au procès de ces attaques. Le complotisme est à la fois un instrument de radicalisation, et un outil pour prolonger l’effroi terroriste." },
  { title: "Du \"Qui ?\" de Cassandre Fristot aux protocoles des Sages de Sion : antisémitisme et complotisme, une longue histoire", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/du-qui-de-cassandre-fristot-aux-protocoles-des-sages-de-sion-antisemitisme-et-complotisme-une-longue-histoire-4576382", img: "assets/episodes/8fec5ca4-614b-40ac-8620-8f21125cdb5c.webp", youtube: null, description: "Rudy Reichstadt, directeur de Conspiracy Watch, et Tristan Mendès France, maître de conférence associé et membre de l’observatoire du conspirationnisme, reviennent sur les thèses complotistes qui se sont propagées durant la crise sanitaire et décryptent les liens entre antisémitisme et complotisme." },
  { title: "Commission Bronner, régulation des réseaux sociaux : comment lutter contre l’essor du complotisme ?", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/commission-bronner-regulation-des-reseaux-sociaux-education-aux-medias-comment-lutter-contre-l-essor-du-complotisme-9263729", img: "assets/episodes/e6404f07-5302-4fb4-9419-9a7fa0a96643.webp", youtube: null, description: "Par quels moyens endiguer la propagation des théories du complot ? À l’occasion du lancement de la commission Bronner, zoom sur les questions et obstacles rencontrés dans cette lutte." },
  { title: "De Dune à Matrix en passant par X-Files : fiction et complotisme", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/de-dune-a-matrix-en-passant-par-x-files-fiction-et-complotisme-8060629", img: "assets/episodes/4dfcd423-3a0a-427c-9243-56f47145362f.webp", youtube: null, description: "Dune, le film événement de la rentrée, est l’une des grandes histoires fictionnelles truffées de complots. Si ces derniers inspirent depuis toujours la fiction, il arrive aussi comme avec Matrix que la fiction inspire le complotisme contemporain." },
  { title: "Du complotisme au sein des manifestations contre le pass sanitaire", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/du-complotisme-au-sein-des-manifestations-contre-le-pass-sanitaire-2257834", img: "assets/episodes/8dc1f322-0359-4820-8eee-ff2b13448ece.webp", youtube: null, description: "Les manifestations contre le pass sanitaire, chaque samedi depuis le début de l’été, attirent certaines figures de la complosphère, et traduisent dans le réel certains discours extrémistes ayant pris leur essor en ligne." },
  { title: "Le 11 septembre, point de bascule du complotisme", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/le-11-septembre-point-de-bascule-du-complotisme-2355188", img: "assets/episodes/045aaee6-80f6-4303-b7bc-cbe7faac6853.webp", youtube: null, description: "Cela fait 20 ans cette année que ces attaques ont frappé les Etats-Unis, 20 ans aussi que les attentats du 11 septembre nourrissent de folles théories, parfois élaborées en France." },
  { title: "Les plateformes, pilier du complotisme", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/les-plateformes-pilier-du-complotisme-5269575", img: "assets/episodes/b948fbe4-b519-4cf7-bf79-cf548f68aa9d.webp", youtube: null, description: "L’avènement d’internet, des sites et des réseaux sociaux, ces plateformes et leurs algorithmes ont donné naissance à l’état des lieux actuel du complotisme." },
  { title: "Thomas Pesquet hypnotisé par la CIA, aliens, platisme : la conquête complotiste de l’espace", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/thomas-pesquet-hypnotise-par-la-cia-aliens-platisme-la-conquete-complotiste-de-l-espace-8901240", img: "assets/episodes/3d59ebd3-5926-452f-9ad4-b7321da4def7.webp", youtube: null, description: "Reptiliens, platistes, ou encore supposée supercherie du voyage de l’Homme sur la Lune : les théories du complot n’épargnent pas l’espace, et ne sont pas que folkloriques." },
  { title: "Régionales : ces complotistes aux ambitions politiques", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/regionales-ces-complotistes-aux-ambitions-politiques-6872217", img: "assets/episodes/463132fc-28fa-4f87-b07d-49c21c0d5cc8.webp", youtube: null, description: "Plusieurs listes aux relents complotistes sont en lice aux prochaines régionales, poussées par le covido-scepticisme." },
  { title: "De Francis Lalanne à Kim Glow : ces \"people\" séduits par les théories du complot", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/de-francis-lalanne-a-kim-glow-ces-people-seduits-par-les-theories-du-complot-2763645", img: "assets/episodes/4852c8cb-9ac0-4b4f-a4f8-10b02fbfd2d4.webp", youtube: null, description: "À la télévision ou sur les réseaux sociaux, certaines personnalités relaient auprès d" },
  { title: "Affaire Mia : un enlèvement d’enfant sur fond de complotisme", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/affaire-mia-un-enlevement-d-enfant-sur-fond-de-complotisme-8404106", img: "assets/episodes/6284f980-6883-48a4-8e52-0e722ea35a3b.webp", youtube: null, description: "Un gourou conspirationniste, des ravisseurs survivalistes, une mère adepte de théories du complot… l’affaire Mia renvoie à l’une des théories les plus partagées par la complosphère : celle d’une pédocriminalité organisée à l’échelle mondiale par les élites et les autorités." },
  { title: "Vaccin contre le Covid-19 : la flambée \"antivax\" complotiste en France", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/vaccin-contre-le-covid-19-la-flambee-antivax-complotiste-en-france-9183131", img: "assets/episodes/7f4381d7-89cb-40ec-a54a-b8c5818c5ba5.webp", youtube: null, description: "Face aux réelles inconnues et aux contradictions dans la communication quant aux vaccins contre le Covid-19, la tendance anti-vaccin s’accélère. Le doute s" },
  { title: "Des reclus de Monflanquin à Vivian Kubrick : dérives sectaires et complotisme", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/des-reclus-de-monflanquin-a-vivian-kubrick-derives-sectaires-et-complotisme-6124557", img: "assets/episodes/ebb3e692-114c-48a3-9721-da8de0e3b665.webp", youtube: null, description: "Dans les affaires Xavier Dupont de Ligonnès ou des reclus de Monflanquin, il est question d" },
  { title: "Dissolution de Génération identitaire : les liens qui unissent droite radicale et complotisme", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/dissolution-de-generation-identitaire-les-liens-qui-unissent-droite-radicale-et-complotisme-9817801", img: "assets/episodes/e7a43587-57c8-4ef9-9d4c-e3360c0f0f6b.webp", youtube: null, description: "Théorie du grand remplacement ou remigration, certains concepts et symboles sont communs à la sphère complotiste et à la droite radicale, comme par exemple Génération identitaire." },
  { title: "Russie, Chine, Iran : géopolitique du complotisme", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/russie-chine-iran-geopolitique-du-complotisme-5018814", img: "assets/episodes/9c1b20c9-517b-4483-aaa7-67c6da8dac74.webp", youtube: null, description: "Rudy Reichstadt, directeur de Conspiracy Watch, et Tristan Mendès France, maître de conférences associé et membre de l’observatoire du conspirationnisme, décryptent les phénomènes complotistes en lien avec l" },
  { title: "Les complotistes et le business du Covid-19", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/les-complotistes-et-le-business-du-covid-19-4467590", img: "assets/episodes/164c2b2c-6410-4067-af59-0408e34d65ea.webp", youtube: null, description: "Rudy Reichstadt, directeur de Conspiracy Watch, et Tristan Mendès France, maître de conférences associé et membre de l’observatoire du conspirationnisme, décryptent les phénomènes complotistes en lien avec l" },
  { title: "États-Unis : les complotistes et l'après Donald Trump", url: "https://www.radiofrance.fr/franceinfo/podcasts/complorama/etats-unis-les-complotistes-et-l-apres-donald-trump-7971806", img: "assets/episodes/9a3943a1-97a6-4648-8b3d-e9636e90a166.webp", youtube: null, description: "Rudy Reichstadt, directeur de Conspiracy Watch, et Tristan Mendès France, maître de conférence associé et membre de l’observatoire du conspirationnisme, décryptent les phénomènes complotistes en lien avec l" },
];

// Deduplicate by exact title (Radio France lists some episodes under
// multiple URLs — keep the first occurrence).
const _seen = new Set();
const _unique = [];
for (const ep of RAW_EPISODES) {
  if (_seen.has(ep.title)) continue;
  _seen.add(ep.title);
  _unique.push(ep);
}

// Anchor episode numbers on "PODCAST. La 100e de Complorama". If the anchor
// is at index N (0-based), then index 0 = episode (N + 100). Falls back to
// counting from the array length if the anchor is missing.
const _anchorIdx = _unique.findIndex(e => /\b100e\b/i.test(e.title));
const TOP_NUMBER = _anchorIdx >= 0 ? _anchorIdx + 100 : _unique.length;

window.EPISODES = _unique.map((ep, i) => {
  const out = {
    n: TOP_NUMBER - i,
    title: ep.title,
    img: ep.img,
    url: ep.url,
  };
  if (ep.youtube) out.youtube = ep.youtube;
  if (ep.description) out.description = ep.description;
  return out;
});
